### YamlMime:YamlDocument
documentType: LandingData
title: Ansible in Azure-documentatie
metadata:
  title: Ansible in Azure-documentatie - zelfstudies, voorbeelden, verwijzingen en resources
  meta.description: Learn how to use Ansible to automate cloud provisioning, configuration management, and application deployments.
  services: terraform
  author: tomarcher
  manager: routlaw
  ms.service: ansible
  ms.tgt_pltfrm: na
  ms.devlang: devops
  ms.topic: landing-page
  ms.date: 07/05/2018
  ms.author: tarcher
  ms.openlocfilehash: 3d885c6374530884e761ecbee837d6406dd3e894
  ms.sourcegitcommit: ab3b2482704758ed13cccafcf24345e833ceaff3
  ms.translationtype: HT
  ms.contentlocale: nl-NL
  ms.lasthandoff: 07/06/2018
  ms.locfileid: "37868602"
abstract:
  description: Gebruik <a href="http://www.ansible.com">Ansible</a> om cloudinrichting, configuratiebeheer en toepassingsimplementaties te automatiseren.
sections:
- title: QuickStarts van vijf minuten
  items:
  - type: paragraph
    text: Ansible configureren en gebruiken om een Linux-VM te maken in Azure.
  - type: list
    style: icon48
    items:
    - image:
        src: /azure/media/index/azure_dev-9.svg
      text: Ansible configureren
      href: /azure/virtual-machines/linux/ansible-install-configure?toc=%2Fen-us%2Fazure%2Fansible%2Ftoc.json&bc=%2Fen-us%2Fazure%2Fbread%2Ftoc.json
    - image:
        src: /azure/media/index/VirtualMachine.svg
      text: Een Linux-VM maken
      href: /azure/virtual-machines/linux/ansible-create-vm?toc=%2Fen-us%2Fazure%2Fansible%2Ftoc.json&bc=%2Fen-us%2Fazure%2Fbread%2Ftoc.json
- title: Zelfstudies met stapsgewijze instructies
  items:
  - type: paragraph
    text: Informatie over hoe u Ansible gebruikt om berekenings- en netwerkinfrastructuur te maken in Azure.
  - type: list
    style: unordered
    items:
    - html: <a href="/azure/virtual-machines/linux/ansible-create-complete-vm?toc=%2Fen-us%2Fazure%2Fansible%2Ftoc.json&bc=%2Fen-us%2Fazure%2Fbread%2Ftoc.json">Maak een virtuele Linux-machine, inclusief een virtueel netwerk, een openbaar IP-adres en een virtuele netwerkinterfacekaart.</a>
    - html: <a href="./ansible-run-playbook-in-cloudshell">Maak verbinding met een virtuele Azure-machine en voer een Ansible-playbook uit in Cloud Shell.</a>
    - html: <a href="./ansible-manage-azure-dynamic-inventories">Maak en beheer een dynamische voorraad van uw Azure-resources.</a>
- title: Naslaginformatie
  items:
  - type: list
    style: cards
    className: cardsD
    items:
    - title: Playbook-rollen
      html: <p><a href="https://galaxy.ansible.com/Azure/azure_preview_modules/">azure_preview_module</a></p>
    - title: Versies en functies
      html: <p><a href="./ansible-matrix.md">Matrix van functies voor modules en rollen</a></p>
    - title: Hulpprogramma's
      html: <p><a href="https://marketplace.visualstudio.com/items?itemName=vscoss.vscode-ansible">Visual Studio Code-extensie voor Ansible</a></p>
