### YamlMime:YamlDocument
documentType: LandingData
title: Ansible in Azure-documentatie
metadata:
  title: Ansible in Azure-documentatie - zelfstudies, voorbeelden, verwijzingen en resources
  meta.description: Learn how to use Ansible to automate cloud provisioning, configuration management, and application deployments.
  services: terraform
  author: tomarcher
  manager: routlaw
  ms.service: ansible
  ms.tgt_pltfrm: na
  ms.devlang: devops
  ms.topic: landing-page
  ms.date: 07/16/2018
  ms.author: tarcher
  ms.openlocfilehash: 1230422d4d33356938aaa9215479b290b56f22e5
  ms.sourcegitcommit: e32ea47d9d8158747eaf8fee6ebdd238d3ba01f7
  ms.translationtype: HT
  ms.contentlocale: nl-NL
  ms.lasthandoff: 07/17/2018
  ms.locfileid: "39089671"
abstract:
  description: Gebruik <a href="http://www.ansible.com">Ansible</a> om cloudinrichting, configuratiebeheer en toepassingsimplementaties te automatiseren.
sections:
- title: QuickStarts van vijf minuten
  items:
  - type: paragraph
    text: Ansible configureren en gebruiken om een Linux-VM te maken in Azure.
  - type: list
    style: icon48
    items:
    - image:
        src: /azure/media/index/azure_dev-9.svg
      text: Ansible configureren
      href: /azure/virtual-machines/linux/ansible-install-configure?toc=%2Fen-us%2Fazure%2Fansible%2Ftoc.json&bc=%2Fen-us%2Fazure%2Fbread%2Ftoc.json
    - image:
        src: /azure/media/index/VirtualMachine.svg
      text: Een Linux-VM maken
      href: /azure/virtual-machines/linux/ansible-create-vm?toc=%2Fen-us%2Fazure%2Fansible%2Ftoc.json&bc=%2Fen-us%2Fazure%2Fbread%2Ftoc.json
- title: Zelfstudies met stapsgewijze instructies
  items:
  - type: paragraph
    text: Leer hoe u Ansible gebruikt om berekening-, netwerk- en opslaginfrastructuur te maken in Azure.
  - type: list
    style: unordered
    items:
    - html: <a href="/azure/virtual-machines/linux/ansible-create-complete-vm?toc=%2Fen-us%2Fazure%2Fansible%2Ftoc.json&bc=%2Fen-us%2Fazure%2Fbread%2Ftoc.json">Maak een virtuele Linux-machine, inclusief een virtueel netwerk, een openbaar IP-adres en een virtuele netwerkinterfacekaart.</a>
    - html: <a href="./ansible-run-playbook-in-cloudshell">Maak verbinding met een virtuele Azure-machine en voer een Ansible-playbook uit in Cloud Shell.</a>
    - html: <a href="./ansible-manage-azure-dynamic-inventories">Maak en beheer een dynamische voorraad van uw Azure-resources.</a>
    - html: <a href="./ansible-create-configure-vmss">Maak en beheer schaalsets voor virtuele machines in Azure.</a>
    - html: <a href="./ansible-deploy-app-vmss">Implementeer toepassingen in schaalsets voor virtuele machines in Azure.</a>
    - html: <a href="./ansible-create-configure-aks">Maak en beheer Azure Kubernetes Service-clusters.</a>
- title: Naslaginformatie
  items:
  - type: list
    style: cards
    className: cardsD
    items:
    - title: Playbook-rollen
      html: <p><a href="https://galaxy.ansible.com/Azure/azure_preview_modules/">azure_preview_module</a></p>
    - title: Versies en functies
      html: <p><a href="./ansible-matrix.md">Matrix van functies voor modules en rollen</a></p>
    - title: Hulpprogramma's
      html: <p><a href="https://marketplace.visualstudio.com/items?itemName=vscoss.vscode-ansible">Visual Studio Code-extensie voor Ansible</a></p>
